- src/pspg.c
Please Revert FreeBSD related defines introduced in d48ad4f
I added a proper FreeBSD port and these defines are not needed anymore.
> Remove FreeBSD build hacks

- Makefile
- config.make.in
Use $(RM) in clean target to avoid failing if the executable is not
present.
Add @CURSES_CFLAGS@ in config.make.inc to fix the build on Debian
Stretch with libncursesw5-dev
> Improve Makefile to better support Debian/Ubuntu packaging

- README.md
I/Gentoo have added an ebuild to the main repository. pspg can now be installed with any Gentoo package manager.
> Add Gentoo installation instruction

- README.md
FreeBSD now has pspg port and prebuit package.
> add FreeBSD installation instruction

- src/pspg.c
GNU Hurd does not define a static MAXPATHLEN because it does not have
such a limit. Define it anyway here so we can use it for buffers.
Debian hurd-i386 build log: https://buildd.debian.org/status/fetch.php?pkg=pspg&arch=hurd-i386&ver=0.5-1&stamp=1511137285&raw=0
> Define MAXPATHLEN on platforms that do not provide it

- tools/m4_ax_with_curses_extra.m4
These autohells macros do not find panel.h in the root of the library path when ncursesw variant is detected. This patch fixes the macros to search both ncursesw/ subdirectory and the root of the library path.
Based on https://github.com/crosstool-ng/crosstool-ng/blob/master/m4/ax_with_curses_extra.m4
> fix ax_with_curses_extra to find <panel.h>

- src/pspg.c
A build from master failed for me because the type `wint_t` wasn't found. This type was referenced on line 1743, in an #if block predicated on the condition `NCURSES_WIDECHAR > 0`. The only time the variables defined in this block are referenced are also inside of an #if block, this time predicated by the additional condition `NCURSES_WIDECHAR > 0 && defined HAVE_NCURSESW`. It seems to be an error that this extra condition was omitted from the first preprocessor block.
My compiler version is: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
These are the ncurses libraries I have installed:
```
libncurses5/xenial,now 6.0+20160213-1ubuntu1 amd64 [installed]
libncurses5-dev/xenial,now 6.0+20160213-1ubuntu1 amd64 [installed]
libncursesw5/xenial,now 6.0+20160213-1ubuntu1 amd64 [installed] …
```
> Fix NCURSES_WIDECHAR preprocessor test

- Makefile
Otherwise "-D_FORTIFY_SOURCE=2" is missing on Debian. Spotted by blhc (build log hardening check).
Possibly CPPFLAGS should be added to `config.make.in` as well, but the fix works even without it.
> Makefile: Add CPPFLAGS to compile commands

- src/pretty-csv.c
On FreeBSD 12.1-STABLE amd64:
```
src/pretty-csv.c:528:52: error: use of undeclared identifier 'SIZE_MAX'
width = utf_string_dsplen_multiline(field, SIZE_MAX, &_more_lines, true);
^
src/pretty-csv.c:532:42: error: use of undeclared identifier 'SIZE_MAX'
width = utf_string_dsplen(field, SIZE_MAX);
^
src/pretty-csv.c:974:79: error: use of undeclared identifier 'SIZE_MAX'
desc->headline_char_size = desc->maxx = utf_string_dsplen(desc->headline, SIZE_MAX);
^
3 errors generated.
```
> SIZE_MAX needs stdint.h

- src/pgclient.c
Hi, I am the maintainer of https://ports.macports.org/port/pspg/summary
I was trying to upgrade the port version 2.5.0 and the source failed to compile, due to a missing semicolon.
In order to avoid maintaining a patch downstream, it would be very helpful to have a new point release with this fixed that I could upgrade to.
Thank you!
> fix syntax error, add missing semicolon

- tools/m4_ax_compare_version.m4
`ax_compare_version.m4` is missing in default autoconf installation on FreeBSD, so the build fails with
```
configure:6055: error: possibly undefined macro: AX_COMPARE_VERSION
If this token and others are legitimate, please use m4_pattern_allow.
See the Autoconf documentation.
```
This PR adds the latest version of `ax_compare_version.m4` from https://www.gnu.org/software/autoconf-archive/ax_compare_version.html
> Add tools/m4_ax_compare_version.m4

- src/pspg.c
3.0.6 currently does not build on FreeBSD:
```
src/pspg.c:991:63: error: use of undeclared identifier 'SIZE_MAX'
size_t prompt_dsplen = utf_string_dsplen(rl_display_prompt, SIZE_MAX);
```
^ This needs `stdint.h` include. There's also a warning:
```
src/pspg.c:2655:17: warning: address of array 'state.pathname' will always evaluate to 'true' [-Wpointer-bool-conversion]
if (state.pathname)
~~  ~~~~~~^~~~~~~~
```
I'm not quite sure what would be the correct fix here, perhaps `if (state.pathname[0])`?
> Unbreak FreeBSD build

- src/pspg.c
There is a small typo in src/pspg.c.
Should read `useless` rather than `useles`.
> docs: fix simple typo, useles -> useless

- src/print.c
- src/st_menu.c
There is a small typo in src/print.c, src/st_menu.c.
Should read `position` rather than `possition`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, possition -> position

- README.md
PrestoSQL was rebranded as Trino: https://trino.io/blog/2020/12/27/announcing-trino.html
> Rename Presto SQL to Trino

- README.md
`usql` [0.9.0](https://github.com/xo/usql/releases/tag/v0.9.0) has just been released, with support for a pager. It should work great with `pspg`.
`usql` is a universal SQL client, modeled after `psql` but it works with almost any databases that have a Go driver implementing the `database/sql` interface.
> Add usql to README

- README.md
Using the pre-compiled binary packages is the encouraged way to install programs on OpenBSD.
+cc @fluca1978, thanks for adding them in the first place! :-)
> change the install instruction for OpenBSD

- src/export.c
clang complained about `colno` being set but not read.  I don't know if it should be used, pspg seems to work fine compiled with this diff in.
> remove unused variable `colno'

- src/pgclient.c
- src/pspg.c
Hello,
straightforwardly, this replaces some `sprintf` with a bounded `snprintf`.  It was brought to my attention by the linker on OpenBSD:
```
pspg.c(pspg.o:(main)): warning: sprintf() is often misused, please use snprintf()
```
> replace sprintf with snprintf

- configure.ac
This improves error message from autogen.sh when autoconf is too old.
Before:
```console
$ ./autogen.sh
configure.ac:12: error: possibly undefined macro: AC_CHECK_INCLUDES_DEFAULT
If this token and others are legitimate, please use m4_pattern_allow.
See the Autoconf documentation.
```
After:
```console
$ ./autogen.sh
configure.ac:1: error: Autoconf version 2.70 or higher is required
configure.ac:1: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
aclocal: error: echo failed with exit status: 63
```
> Declare minimum required autoconf version

- scripts/sqlcl/pspg.sql
If sqlcl is started with `/nolog` argument and the `connect` command is used afterwards, `pspg` fails as described in issue #228. If you connect directly using a connect string provided as an argument, `pspg` is working for the current session only. As soon as a new `connect` is issued, all subsequent `pspg` command will fail with `SQL Error: Closed Connection`.
This patch ensures that the current sqlcl connection handler is always assigned to the sqlcl executor.
> Fix for issue #228.
